// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PocketGrail.Infrastructure;

#nullable disable

namespace PocketGrail.Infrastructure.Migrations
{
    [DbContext(typeof(PocketGrailDbContext))]
    [Migration("20260518141810_AddClassRacePrerequisiteData")]
    partial class AddClassRacePrerequisiteData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterFeature", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("FeaturesId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "FeaturesId");

                    b.HasIndex("FeaturesId");

                    b.ToTable("CharacterFeature");
                });

            modelBuilder.Entity("CharacterProficienciesArmorProficiencies", b =>
                {
                    b.Property<int>("ArmorsId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterProficienciesId")
                        .HasColumnType("integer");

                    b.HasKey("ArmorsId", "CharacterProficienciesId");

                    b.HasIndex("CharacterProficienciesId");

                    b.ToTable("CharacterProficienciesArmorProficiencies");
                });

            modelBuilder.Entity("CharacterProficienciesInstruments", b =>
                {
                    b.Property<int>("CharacterProficienciesId")
                        .HasColumnType("integer");

                    b.Property<int>("InstrumentsId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterProficienciesId", "InstrumentsId");

                    b.HasIndex("InstrumentsId");

                    b.ToTable("CharacterProficienciesInstruments");
                });

            modelBuilder.Entity("CharacterProficienciesLanguages", b =>
                {
                    b.Property<int>("CharacterProficienciesId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterProficienciesId", "LanguagesId");

                    b.HasIndex("LanguagesId");

                    b.ToTable("CharacterProficienciesLanguages");
                });

            modelBuilder.Entity("CharacterProficienciesWeaponProficiencies", b =>
                {
                    b.Property<int>("CharacterProficienciesId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponsId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterProficienciesId", "WeaponsId");

                    b.HasIndex("WeaponsId");

                    b.ToTable("CharacterProficienciesWeaponProficiencies");
                });

            modelBuilder.Entity("ClassFeatureArmorGrants", b =>
                {
                    b.Property<int>("ArmorGrantsId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassFeatureId")
                        .HasColumnType("integer");

                    b.HasKey("ArmorGrantsId", "ClassFeatureId");

                    b.HasIndex("ClassFeatureId");

                    b.ToTable("ClassFeatureArmorGrants");
                });

            modelBuilder.Entity("ClassFeatureInstrumentGrants", b =>
                {
                    b.Property<int>("ClassFeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("InstrumentGrantsId")
                        .HasColumnType("integer");

                    b.HasKey("ClassFeatureId", "InstrumentGrantsId");

                    b.HasIndex("InstrumentGrantsId");

                    b.ToTable("ClassFeatureInstrumentGrants");
                });

            modelBuilder.Entity("ClassFeatureLanguageGrants", b =>
                {
                    b.Property<int>("ClassFeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageGrantsId")
                        .HasColumnType("integer");

                    b.HasKey("ClassFeatureId", "LanguageGrantsId");

                    b.HasIndex("LanguageGrantsId");

                    b.ToTable("ClassFeatureLanguageGrants");
                });

            modelBuilder.Entity("ClassFeatureWeaponGrants", b =>
                {
                    b.Property<int>("ClassFeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponGrantsId")
                        .HasColumnType("integer");

                    b.HasKey("ClassFeatureId", "WeaponGrantsId");

                    b.HasIndex("WeaponGrantsId");

                    b.ToTable("ClassFeatureWeaponGrants");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DmOwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionCode")
                        .IsUnique();

                    b.HasIndex("DmOwnerId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.CampaignParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("CampaignParticipants");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alignment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Appearance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("BackgroundStory")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("DeathFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DeathSuccesses")
                        .HasColumnType("integer");

                    b.Property<int>("Exhaustion")
                        .HasColumnType("integer");

                    b.Property<bool>("HasInspiration")
                        .HasColumnType("boolean");

                    b.Property<float?>("ImageCropHeight")
                        .HasColumnType("real");

                    b.Property<float?>("ImageCropWidth")
                        .HasColumnType("real");

                    b.Property<float?>("ImageCropX")
                        .HasColumnType("real");

                    b.Property<float?>("ImageCropY")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("TempHp")
                        .HasColumnType("integer");

                    b.Property<int>("TotalHitDiceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedHitDice")
                        .HasColumnType("integer");

                    b.Property<int>("XpPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int?>("CharacterSubclassId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalHitDiceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSubclassId");

                    b.HasIndex("ClassId");

                    b.HasIndex("CharacterId", "ClassId")
                        .IsUnique();

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterFeat", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "FeatId");

                    b.HasIndex("FeatId");

                    b.ToTable("CharacterFeats");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterItem", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAttuned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterSpell", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer");

                    b.Property<bool>("Prepared")
                        .HasColumnType("boolean");

                    b.HasKey("CharacterId", "SpellId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("CpCoins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EpCoins")
                        .HasColumnType("integer");

                    b.Property<int>("GpCoins")
                        .HasColumnType("integer");

                    b.Property<int>("PpCoins")
                        .HasColumnType("integer");

                    b.Property<int>("SpCoins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterWallets");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtkMod")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChargesInfo")
                        .HasColumnType("text");

                    b.Property<string>("Cost")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<string>("DamageType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsMagical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RechargeType")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeaponProperties")
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortDesсription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillChoiceCount")
                        .HasColumnType("integer");

                    b.Property<string>("SpellAbility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalHitDice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedHitDice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.ClassSavingThrowProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "Ability")
                        .IsUnique();

                    b.ToTable("ClassSavingThrowProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.ClassSpellSlotTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpellSlotLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "ClassLevel", "SpellSlotLevel")
                        .IsUnique();

                    b.ToTable("ClassSpellSlotTemplates");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.MulticlassPrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinimumScore")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAbility")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "RequiredAbility")
                        .IsUnique();

                    b.ToTable("MulticlassPrerequisites");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.Subclass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Subclasses");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Feat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requirement")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasDiscriminator().HasValue("Feature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Proficiencies.AdditionalSavingThrowProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CharacterProficienciesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterProficienciesId", "Ability")
                        .IsUnique();

                    b.ToTable("AdditionalSavingThrowProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Proficiencies.ArmorProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ArmorProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Proficiencies.SkillProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterProficienciesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasExpertise")
                        .HasColumnType("boolean");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterProficienciesId", "Skill")
                        .IsUnique();

                    b.ToTable("SkillProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Proficiencies.WeaponProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WeaponProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("ChaBonus")
                        .HasColumnType("integer");

                    b.Property<int>("ConBonus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DexBonus")
                        .HasColumnType("integer");

                    b.Property<int>("FlexibleBonusPoints")
                        .HasColumnType("integer");

                    b.Property<int>("IntBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StrBonus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WisBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CastingTime")
                        .HasColumnType("text");

                    b.Property<string>("Components")
                        .HasColumnType("text");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRitual")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .HasColumnType("text");

                    b.Property<string>("School")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.SpellSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemainingSlots")
                        .HasColumnType("integer");

                    b.Property<int>("SlotLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("SpellSlots");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RaceArmorGrants", b =>
                {
                    b.Property<int>("ArmorGrantsId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("ArmorGrantsId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceArmorGrants");
                });

            modelBuilder.Entity("RaceInstrumentGrants", b =>
                {
                    b.Property<int>("InstrumentGrantsId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("InstrumentGrantsId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceInstrumentGrants");
                });

            modelBuilder.Entity("RaceLanguageGrants", b =>
                {
                    b.Property<int>("LanguageGrantsId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("LanguageGrantsId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceLanguageGrants");
                });

            modelBuilder.Entity("RaceWeaponGrants", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponGrantsId")
                        .HasColumnType("integer");

                    b.HasKey("RaceId", "WeaponGrantsId");

                    b.HasIndex("WeaponGrantsId");

                    b.ToTable("RaceWeaponGrants");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.ClassFeature", b =>
                {
                    b.HasBaseType("PocketGrail.Domain.Entities.Feature");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("GainingLevel")
                        .HasColumnType("integer");

                    b.HasIndex("ClassId");

                    b.HasDiscriminator().HasValue("ClassFeature");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.RaceFeature", b =>
                {
                    b.HasBaseType("PocketGrail.Domain.Entities.Feature");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasIndex("RaceId");

                    b.HasDiscriminator().HasValue("RaceFeature");
                });

            modelBuilder.Entity("CharacterFeature", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterProficienciesArmorProficiencies", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Proficiencies.ArmorProficiency", null)
                        .WithMany()
                        .HasForeignKey("ArmorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", null)
                        .WithMany()
                        .HasForeignKey("CharacterProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterProficienciesInstruments", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", null)
                        .WithMany()
                        .HasForeignKey("CharacterProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterProficienciesLanguages", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", null)
                        .WithMany()
                        .HasForeignKey("CharacterProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterProficienciesWeaponProficiencies", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", null)
                        .WithMany()
                        .HasForeignKey("CharacterProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Proficiencies.WeaponProficiency", null)
                        .WithMany()
                        .HasForeignKey("WeaponsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassFeatureArmorGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Proficiencies.ArmorProficiency", null)
                        .WithMany()
                        .HasForeignKey("ArmorGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.ClassFeature", null)
                        .WithMany()
                        .HasForeignKey("ClassFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassFeatureInstrumentGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.ClassFeature", null)
                        .WithMany()
                        .HasForeignKey("ClassFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassFeatureLanguageGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.ClassFeature", null)
                        .WithMany()
                        .HasForeignKey("ClassFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassFeatureWeaponGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.ClassFeature", null)
                        .WithMany()
                        .HasForeignKey("ClassFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Proficiencies.WeaponProficiency", null)
                        .WithMany()
                        .HasForeignKey("WeaponGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.User", "DmOwner")
                        .WithMany()
                        .HasForeignKey("DmOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DmOwner");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.CampaignParticipant", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Participants")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.Character", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PocketGrail.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterClass", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Subclass", "CharacterSubclass")
                        .WithMany()
                        .HasForeignKey("CharacterSubclassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CharacterSubclass");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterFeat", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Feat", "Feat")
                        .WithMany()
                        .HasForeignKey("FeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Feat");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterItem", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Characters.Item", "Item")
                        .WithMany("CharacterItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithOne("Proficiencies")
                        .HasForeignKey("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterSpell", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Spell", "Spell")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterStats", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithOne("CharacterStats")
                        .HasForeignKey("PocketGrail.Domain.Entities.Characters.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterWallet", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithOne("Wallet")
                        .HasForeignKey("PocketGrail.Domain.Entities.Characters.CharacterWallet", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.ClassSavingThrowProficiency", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Class", "Class")
                        .WithMany("SavingThrows")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.ClassSpellSlotTemplate", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Class", "Class")
                        .WithMany("SpellSlotTemplates")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.MulticlassPrerequisite", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Class", "Class")
                        .WithMany("MulticlassPrerequisites")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.Subclass", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Class", "SourceClass")
                        .WithMany("Subclasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceClass");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Proficiencies.AdditionalSavingThrowProficiency", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", "CharacterProficiencies")
                        .WithMany("AdditionalSavingThrows")
                        .HasForeignKey("CharacterProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Proficiencies.SkillProficiency", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", "CharacterProficiencies")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterProficiencies");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.SpellSlot", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Characters.Character", "Character")
                        .WithMany("SpellSlots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RaceArmorGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Proficiencies.ArmorProficiency", null)
                        .WithMany()
                        .HasForeignKey("ArmorGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceInstrumentGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceLanguageGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceWeaponGrants", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocketGrail.Domain.Entities.Proficiencies.WeaponProficiency", null)
                        .WithMany()
                        .HasForeignKey("WeaponGrantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.ClassFeature", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.ClassEntities.Class", "SourceClass")
                        .WithMany("ClassFeatures")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceClass");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.RaceFeature", b =>
                {
                    b.HasOne("PocketGrail.Domain.Entities.Race", "SourceRace")
                        .WithMany("Features")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceRace");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.Character", b =>
                {
                    b.Navigation("CharacterStats");

                    b.Navigation("Classes");

                    b.Navigation("Proficiencies");

                    b.Navigation("SpellSlots");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.CharacterProficiencies", b =>
                {
                    b.Navigation("AdditionalSavingThrows");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Characters.Item", b =>
                {
                    b.Navigation("CharacterItems");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.ClassEntities.Class", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ClassFeatures");

                    b.Navigation("MulticlassPrerequisites");

                    b.Navigation("SavingThrows");

                    b.Navigation("SpellSlotTemplates");

                    b.Navigation("Subclasses");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Race", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("PocketGrail.Domain.Entities.Spell", b =>
                {
                    b.Navigation("CharacterSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
