using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PocketGrail.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class IdTypeIntAndAddUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""Participants"" DROP CONSTRAINT ""FK_Participants_Sessions_SessionId"";");

            migrationBuilder.Sql(@"DROP INDEX ""IX_Sessions_Code"";");

            migrationBuilder.Sql(@"TRUNCATE TABLE ""Participants"", ""Sessions"" RESTART IDENTITY CASCADE;");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Sessions""
                    ALTER COLUMN ""Id"" TYPE integer USING 0,
                    ALTER COLUMN ""Id"" SET DEFAULT 0;
            ");
            migrationBuilder.Sql(@"
                ALTER TABLE ""Sessions""
                    ALTER COLUMN ""Id"" DROP DEFAULT,
                    ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Participants""
                    ALTER COLUMN ""Id"" TYPE integer USING 0,
                    ALTER COLUMN ""Id"" SET DEFAULT 0;
            ");
            migrationBuilder.Sql(@"
                ALTER TABLE ""Participants""
                    ALTER COLUMN ""Id"" DROP DEFAULT,
                    ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1);
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Participants""
                    ALTER COLUMN ""SessionId"" TYPE integer USING 0;
            ");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX ""IX_Sessions_Code"" ON ""Sessions"" (""Code"");");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Participants""
                    ADD CONSTRAINT ""FK_Participants_Sessions_SessionId""
                    FOREIGN KEY (""SessionId"") REFERENCES ""Sessions"" (""Id"") ON DELETE CASCADE;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""Participants"" DROP CONSTRAINT ""FK_Participants_Sessions_SessionId"";");
            migrationBuilder.Sql(@"DROP INDEX ""IX_Sessions_Code"";");
            migrationBuilder.Sql(@"TRUNCATE TABLE ""Participants"", ""Sessions"" RESTART IDENTITY CASCADE;");

            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "Sessions",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<Guid>(
                name: "SessionId",
                table: "Participants",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "Participants",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX ""IX_Sessions_Code"" ON ""Sessions"" (""Code"");");
            migrationBuilder.Sql(@"
                ALTER TABLE ""Participants""
                    ADD CONSTRAINT ""FK_Participants_Sessions_SessionId""
                    FOREIGN KEY (""SessionId"") REFERENCES ""Sessions"" (""Id"") ON DELETE CASCADE;
            ");
        }
    }
}
